export default [
  'control-extension/CCControl.js',
  'control-extension/CCControlButton.js',
  'control-extension/CCControlUtils.js',
  'control-extension/CCInvocation.js',
  'control-extension/CCMenuPassive.js',
  'control-extension/CCControlSaturationBrightnessPicker.js',
  'control-extension/CCControlHuePicker.js',
  'control-extension/CCControlColourPicker.js',
  'control-extension/CCControlSlider.js',
  'control-extension/CCControlSwitch.js',
  'control-extension/CCControlStepper.js',
  'control-extension/CCControlPotentiometer.js',
  'scrollview/CCScrollView.js',
  'scrollview/CCScrollViewCanvasRenderCmd.js',
  'scrollview/CCScrollViewWebGLRenderCmd.js',
  'scrollview/CCSorting.js',
  'scrollview/CCTableView.js'
];
