// Initialize the ccs global namespace before any module runs.
import { Node, Sprite, Component } from "@aspect/core";

window.ccs = window.ccs || {};

ccs.Node = Node;
ccs.Sprite = Sprite;
ccs.Component = Component;

ccs.cocostudioVersion = "v1.3.0.0";

// ─── Armature ────────────────────────────────────────────────────────────────
export * from './armature/armature-define.js';
export * from './armature/utils/data-reader-helper/index.js';
export * from './armature/utils/sprite-frame-cache-helper.js';
export * from './armature/utils/transform-help.js';
export * from './armature/animation/tween-function/index.js';
export * from './armature/utils/util-math.js';
export * from './armature/utils/armature-data-manager.js';
export * from './armature/utils/datas/index.js';
export * from './armature/display/decorative-display.js';
export * from './armature/display/display-factory.js';
export * from './armature/display/display-manager.js';

import { Skin } from './armature/display/skin.js';
import { SkinCanvasRenderCmd, SkinWebGLRenderCmd } from './armature/display/skin-render-cmd.js';
Skin.CanvasRenderCmd = SkinCanvasRenderCmd;
Skin.WebGLRenderCmd = SkinWebGLRenderCmd;
export { Skin } from './armature/display/skin.js';
export * from './armature/display/skin-render-cmd.js';

export * from './armature/animation/process-base.js';
export * from './armature/animation/armature-animation/index.js';
export * from './armature/animation/tween.js';
export * from './armature/physics/collider-detector/index.js';

import { Armature } from './armature/armature.js';
import { ArmatureCanvasRenderCmd } from './armature/armature-canvas-render-cmd.js';
import { ArmatureWebGLRenderCmd } from './armature/armature-webgl-render-cmd.js';
Armature.CanvasRenderCmd = ArmatureCanvasRenderCmd;
Armature.WebGLRenderCmd = ArmatureWebGLRenderCmd;
export { Armature } from './armature/armature.js';
export * from './armature/armature-canvas-render-cmd.js';
export * from './armature/armature-webgl-render-cmd.js';

export * from './armature/bone.js';

// ─── Action ──────────────────────────────────────────────────────────────────
export * from './action/action-frame/index.js';
export * from './action/action-manager.js';
export * from './action/action-node.js';
export * from './action/action-object.js';

// ─── Components ──────────────────────────────────────────────────────────────
export * from './components/com-attribute.js';
export * from './components/com-audio.js';
export * from './components/com-controller.js';
export * from './components/com-render.js';

// ─── Trigger ─────────────────────────────────────────────────────────────────
export * from './trigger/object-factory/index.js';
export * from './trigger/trigger-base.js';
export * from './trigger/trigger-mng/index.js';
export * from './trigger/trigger-obj/index.js';

// ─── Timeline ────────────────────────────────────────────────────────────────
export * from './timeline/action-timeline/index.js';
export * from './timeline/frame/index.js';
export * from './timeline/timeline.js';
export * from './timeline/skin-node.js';
export * from './timeline/bone-node.js';
export * from './timeline/skeleton-node.js';

// ─── Loader ──────────────────────────────────────────────────────────────────
export * from './loader/load/index.js';
import './loader/action-parser.js';
import './loader/timeline-parser.js';

// ─── Globals ─────────────────────────────────────────────────────────────────
import { ActionFadeFrame } from "./action/action-frame/action-fade-frame.js";
import { ActionFrame } from "./action/action-frame/action-frame.js";
import { ActionMoveFrame } from "./action/action-frame/action-move-frame.js";
import { ActionRotationFrame } from "./action/action-frame/action-rotation-frame.js";
import { ActionScaleFrame } from "./action/action-frame/action-scale-frame.js";
import { ActionTintFrame } from "./action/action-frame/action-tint-frame.js";
import { ActionNode } from "./action/action-node.js";
import { ActionObject } from "./action/action-object.js";
import { AnimationEvent } from "./armature/animation/armature-animation/animation-event.js";
import { ArmatureAnimation } from "./armature/animation/armature-animation/armature-animation.js";
import { FrameEvent, MovementEvent } from "./armature/animation/armature-animation/utils.js";
import { ProcessBase } from "./armature/animation/process-base.js";
import { DOUBLE_PI, HALF_PI, M_PI, M_PI_2, M_PI_X_2 } from "./armature/animation/tween-function/constants.js";
import { TweenFunction } from "./armature/animation/tween-function/utils.js";
import { Tween } from "./armature/animation/tween.js";
import { armatureVersion } from "./armature/armature-define.js";
import { Bone } from "./armature/bone.js";
import { DecorativeDisplay } from "./armature/display/decorative-display.js";
import { DisplayManager } from "./armature/display/display-manager.js";
import { ColliderBody } from "./armature/physics/collider-detector/collider-body.js";
import { ColliderDetector } from "./armature/physics/collider-detector/collider-detector.js";
import { ColliderFilter } from "./armature/physics/collider-detector/collider-filter.js";
import { RelativeData } from "./armature/utils/armature-data-manager.js";
import { DataInfo } from "./armature/utils/data-reader-helper/data-reader-helper.js";
import { ArmatureData } from "./armature/utils/datas/armature-data.js";
import { ArmatureDisplayData } from "./armature/utils/datas/armature-display-data.js";
import { BaseData } from "./armature/utils/datas/base-data.js";
import { BoneData } from "./armature/utils/datas/bone-data.js";
import { DisplayData } from "./armature/utils/datas/display-data.js";
import { FrameData } from "./armature/utils/datas/frame-data.js";
import { MovementBoneData } from "./armature/utils/datas/movement-bone-data.js";
import { ParticleDisplayData } from "./armature/utils/datas/particle-display-data.js";
import { SpriteDisplayData } from "./armature/utils/datas/sprite-display-data.js";
import { AnimationData, ContourData, ContourVertex2, MovementData, TextureData } from "./armature/utils/datas/utils.js";
import { TransformHelp } from "./armature/utils/transform-help.js";
import { extBezierTo, extCircleTo, fmodf, isSpriteContainPoint } from "./armature/utils/util-math.js";
import { ComAttribute } from "./components/com-attribute.js";
import { ComAudio } from "./components/com-audio.js";
import { ComController } from "./components/com-controller.js";
import { ComRender } from "./components/com-render.js";
import { _parser } from "./loader/load/parser.js";
import { load, loadWithVisibleSize } from "./loader/load/utils.js";
import { ActionTimelineData } from "./timeline/action-timeline/action-timeline-data.js";
import { ActionTimeline } from "./timeline/action-timeline/action-timeline.js";
import { ComExtensionData } from "./timeline/action-timeline/com-extension-data.js";
import { AnimationInfo } from "./timeline/action-timeline/utils.js";
import { BoneNode, _setSkeletonNodeClass } from "./timeline/bone-node.js";
import { AlphaFrame } from "./timeline/frame/alpha-frame.js";
import { AnchorPointFrame } from "./timeline/frame/anchor-point-frame.js";
import { BlendFuncFrame } from "./timeline/frame/blend-func-frame.js";
import { ColorFrame } from "./timeline/frame/color-frame.js";
import { EventFrame } from "./timeline/frame/event-frame.js";
import { Frame } from "./timeline/frame/frame.js";
import { InnerActionFrame } from "./timeline/frame/inner-action-frame.js";
import { PositionFrame } from "./timeline/frame/position-frame.js";
import { RotationFrame } from "./timeline/frame/rotation-frame.js";
import { RotationSkewFrame } from "./timeline/frame/rotation-skew-frame.js";
import { ScaleFrame } from "./timeline/frame/scale-frame.js";
import { SkewFrame } from "./timeline/frame/skew-frame.js";
import { TextureFrame } from "./timeline/frame/texture-frame.js";
import { VisibleFrame } from "./timeline/frame/visible-frame.js";
import { ZOrderFrame } from "./timeline/frame/z-order-frame.js";
import { SkeletonNode } from "./timeline/skeleton-node.js";
import { SkinNode } from "./timeline/skin-node.js";
import { Timeline } from "./timeline/timeline.js";
import { TInfo } from "./trigger/object-factory/t-info.js";
import { registerTriggerClass, sendEvent } from "./trigger/trigger-base.js";
import { ArmatureMovementDispatcher } from "./trigger/trigger-mng/armature-movement-dispatcher.js";
import { BaseTriggerAction } from "./trigger/trigger-obj/base-trigger-action.js";
import { BaseTriggerCondition } from "./trigger/trigger-obj/base-trigger-condition.js";
import { TriggerObj } from "./trigger/trigger-obj/trigger-obj.js";

ccs.ActionFadeFrame = ActionFadeFrame;
ccs.ActionFrame = ActionFrame;
ccs.ActionMoveFrame = ActionMoveFrame;
ccs.ActionRotationFrame = ActionRotationFrame;
ccs.ActionScaleFrame = ActionScaleFrame;
ccs.ActionTintFrame = ActionTintFrame;
ccs.ActionNode = ActionNode;
ccs.ActionObject = ActionObject;
ccs.AnimationEvent = AnimationEvent;
ccs.ArmatureAnimation = ArmatureAnimation;
ccs.MovementEvent = MovementEvent;
ccs.FrameEvent = FrameEvent;
ccs.ProcessBase = ProcessBase;
ccs.DOUBLE_PI = DOUBLE_PI;
ccs.HALF_PI = HALF_PI;
ccs.M_PI = M_PI;
ccs.M_PI_X_2 = M_PI_X_2;
ccs.M_PI_2 = M_PI_2;
ccs.TweenFunction = TweenFunction;
ccs.Tween = Tween;
ccs.armatureVersion = armatureVersion;
ccs.Armature = Armature;
ccs.Bone = Bone;
ccs.DecorativeDisplay = DecorativeDisplay;
ccs.DisplayManager = DisplayManager;
ccs.Skin = Skin;
ccs.ColliderBody = ColliderBody;
ccs.ColliderDetector = ColliderDetector;
ccs.ColliderFilter = ColliderFilter;
ccs.RelativeData = RelativeData;
ccs.DataInfo = DataInfo;
ccs.ArmatureData = ArmatureData;
ccs.ArmatureDisplayData = ArmatureDisplayData;
ccs.BaseData = BaseData;
ccs.BoneData = BoneData;
ccs.DisplayData = DisplayData;
ccs.FrameData = FrameData;
ccs.MovementBoneData = MovementBoneData;
ccs.ParticleDisplayData = ParticleDisplayData;
ccs.SpriteDisplayData = SpriteDisplayData;
ccs.MovementData = MovementData;
ccs.AnimationData = AnimationData;
ccs.ContourVertex2 = ContourVertex2;
ccs.ContourData = ContourData;
ccs.TextureData = TextureData;
ccs.TransformHelp = TransformHelp;
ccs.fmodf = fmodf;
ccs.isSpriteContainPoint = isSpriteContainPoint;
ccs.extBezierTo = extBezierTo;
ccs.extCircleTo = extCircleTo;
ccs.ComAttribute = ComAttribute;
ccs.ComAudio = ComAudio;
ccs.ComController = ComController;
ccs.ComRender = ComRender;
ccs._parser = _parser;
ccs.load = load;
ccs.loadWithVisibleSize = loadWithVisibleSize;
ccs.ActionTimelineData = ActionTimelineData;
ccs.ActionTimeline = ActionTimeline;
ccs.ComExtensionData = ComExtensionData;
ccs.AnimationInfo = AnimationInfo;
ccs.BoneNode = BoneNode;
ccs.AlphaFrame = AlphaFrame;
ccs.AnchorPointFrame = AnchorPointFrame;
ccs.BlendFuncFrame = BlendFuncFrame;
ccs.ColorFrame = ColorFrame;
ccs.EventFrame = EventFrame;
ccs.Frame = Frame;
ccs.InnerActionFrame = InnerActionFrame;
ccs.PositionFrame = PositionFrame;
ccs.RotationFrame = RotationFrame;
ccs.RotationSkewFrame = RotationSkewFrame;
ccs.ScaleFrame = ScaleFrame;
ccs.SkewFrame = SkewFrame;
ccs.TextureFrame = TextureFrame;
ccs.VisibleFrame = VisibleFrame;
ccs.ZOrderFrame = ZOrderFrame;
ccs.SkeletonNode = SkeletonNode;
_setSkeletonNodeClass(SkeletonNode);
ccs.SkinNode = SkinNode;
ccs.Timeline = Timeline;
ccs.TInfo = TInfo;
ccs.sendEvent = sendEvent;
ccs.registerTriggerClass = registerTriggerClass;
ccs.ArmatureMovementDispatcher = ArmatureMovementDispatcher;
ccs.BaseTriggerAction = BaseTriggerAction;
ccs.BaseTriggerCondition = BaseTriggerCondition;
ccs.TriggerObj = TriggerObj;
import { FRAME_TYPE_FADE, FRAME_TYPE_MAX, FRAME_TYPE_MOVE, FRAME_TYPE_ROTATE, FRAME_TYPE_SCALE, FRAME_TYPE_TINT, FrameEaseType } from "./action/action-frame/constants.js";
import { actionManager } from "./action/action-manager.js";
import { MovementEventType } from "./armature/animation/armature-animation/constants.js";
import { ANIMATION_TYPE_LOOP_BACK, ANIMATION_TYPE_LOOP_FRONT, ANIMATION_TYPE_MAX, ANIMATION_TYPE_NO_LOOP, ANIMATION_TYPE_SINGLE_FRAME, ANIMATION_TYPE_TO_LOOP_BACK, ANIMATION_TYPE_TO_LOOP_FRONT } from "./armature/animation/process-base.js";
import { TweenType } from "./armature/animation/tween-function/constants.js";
import { ARMATURE_MAX_CHILD, ARMATURE_MAX_COUNT, ARMATURE_MAX_ZORDER, AUTO_ADD_SPRITE_FRAME_NAME_PREFIX, ENABLE_PHYSICS_CHIPMUNK_DETECT, ENABLE_PHYSICS_SAVE_CALCULATED_VERTEX, MAX_VERTEXZ_VALUE, VERSION_CHANGE_ROTATION_RANGE, VERSION_COLOR_READING, VERSION_COMBINED } from "./armature/armature-define.js";
import { displayFactory } from "./armature/display/display-factory.js";
import { PT_RATIO } from "./armature/physics/collider-detector/constants.js";
import { armatureDataManager } from "./armature/utils/armature-data-manager.js";
import { CONST_ANIMATION, CONST_ANIMATIONS, CONST_ANIMATION_DATA, CONST_ARMATURE, CONST_ARMATURES, CONST_ARMATURE_DATA, CONST_A_ALPHA, CONST_A_ALPHA_OFFSET, CONST_A_BLEND_DST, CONST_A_BLEND_SRC, CONST_A_BLEND_TYPE, CONST_A_BLUE, CONST_A_BLUE_OFFSET, CONST_A_COCOS2DX_X, CONST_A_COCOS2DX_Y, CONST_A_COCOS2D_PIVOT_X, CONST_A_COCOS2D_PIVOT_Y, CONST_A_COLOR_TRANSFORM, CONST_A_DISPLAY_INDEX, CONST_A_DISPLAY_TYPE, CONST_A_DURATION, CONST_A_DURATION_TO, CONST_A_DURATION_TWEEN, CONST_A_EASING_PARAM, CONST_A_EVENT, CONST_A_FRAME_INDEX, CONST_A_GREEN, CONST_A_GREEN_OFFSET, CONST_A_HEIGHT, CONST_A_IS_ARMATURE, CONST_A_LOOP, CONST_A_MOVEMENT, CONST_A_MOVEMENT_DELAY, CONST_A_MOVEMENT_SCALE, CONST_A_NAME, CONST_A_PARENT, CONST_A_PIVOT_X, CONST_A_PIVOT_Y, CONST_A_PLIST, CONST_A_RED, CONST_A_RED_OFFSET, CONST_A_SCALE_X, CONST_A_SCALE_Y, CONST_A_SKEW_X, CONST_A_SKEW_Y, CONST_A_SOUND, CONST_A_SOUND_EFFECT, CONST_A_TWEEN_EASING, CONST_A_TWEEN_FRAME, CONST_A_TWEEN_ROTATE, CONST_A_WIDTH, CONST_A_X, CONST_A_Y, CONST_A_Z, CONST_BONE, CONST_BONE_DATA, CONST_COLOR_INFO, CONST_CONFIG_FILE_PATH, CONST_CONTENT_SCALE, CONST_CONTOUR, CONST_CONTOUR_DATA, CONST_CONTOUR_VERTEX, CONST_DISPLAY, CONST_DISPLAY_DATA, CONST_FL_NAN, CONST_FRAME, CONST_FRAME_DATA, CONST_MOVEMENT, CONST_MOVEMENT_BONE_DATA, CONST_MOVEMENT_DATA, CONST_SKELETON, CONST_SKIN_DATA, CONST_SUB_TEXTURE, CONST_TEXTURE_ATLAS, CONST_TEXTURE_DATA, CONST_VERSION, CONST_VERSION_2_0, CONST_VERSION_COMBINED, CONST_VERTEX_POINT } from "./armature/utils/data-reader-helper/constants.js";
import { dataReaderHelper } from "./armature/utils/data-reader-helper/data-reader-helper.js";
import { BLEND_TYPE_ADD, BLEND_TYPE_ALPHA, BLEND_TYPE_DARKEN, BLEND_TYPE_DIFFERENCE, BLEND_TYPE_ERASE, BLEND_TYPE_HIGHLIGHT, BLEND_TYPE_INVERT, BLEND_TYPE_LAYER, BLEND_TYPE_LIGHTEN, BLEND_TYPE_MULTIPLY, BLEND_TYPE_NORMAL, BLEND_TYPE_OVERLAY, BLEND_TYPE_SCREEN, BLEND_TYPE_SUBTRACT, DISPLAY_TYPE_ARMATURE, DISPLAY_TYPE_MAX, DISPLAY_TYPE_PARTICLE, DISPLAY_TYPE_SPRITE } from "./armature/utils/datas/constants.js";
import { spriteFrameCacheHelper } from "./armature/utils/sprite-frame-cache-helper.js";
import { SPRITE_CONTAIN_POINT, SPRITE_CONTAIN_POINT_WITH_RETURN } from "./armature/utils/util-math.js";
import { actionTimelineCache } from "./loader/load/action-timeline-cache.js";
import { csLoader } from "./loader/load/cs-loader.js";
import { _ccsLoad } from "./loader/load/utils.js";
import { InnerActionType } from "./timeline/frame/constants.js";
import { objectFactory } from "./trigger/object-factory/object-factory.js";
import { triggerManager } from "./trigger/trigger-mng/trigger-manager.js";

ccs.FRAME_TYPE_MOVE = FRAME_TYPE_MOVE;
ccs.FRAME_TYPE_SCALE = FRAME_TYPE_SCALE;
ccs.FRAME_TYPE_ROTATE = FRAME_TYPE_ROTATE;
ccs.FRAME_TYPE_TINT = FRAME_TYPE_TINT;
ccs.FRAME_TYPE_FADE = FRAME_TYPE_FADE;
ccs.FRAME_TYPE_MAX = FRAME_TYPE_MAX;
ccs.FrameEaseType = FrameEaseType;
ccs.actionManager = actionManager;
ccs.MovementEventType = MovementEventType;
ccs.ANIMATION_TYPE_SINGLE_FRAME = ANIMATION_TYPE_SINGLE_FRAME;
ccs.ANIMATION_TYPE_NO_LOOP = ANIMATION_TYPE_NO_LOOP;
ccs.ANIMATION_TYPE_TO_LOOP_FRONT = ANIMATION_TYPE_TO_LOOP_FRONT;
ccs.ANIMATION_TYPE_TO_LOOP_BACK = ANIMATION_TYPE_TO_LOOP_BACK;
ccs.ANIMATION_TYPE_LOOP_FRONT = ANIMATION_TYPE_LOOP_FRONT;
ccs.ANIMATION_TYPE_LOOP_BACK = ANIMATION_TYPE_LOOP_BACK;
ccs.ANIMATION_TYPE_MAX = ANIMATION_TYPE_MAX;
ccs.TweenType = TweenType;
ccs.VERSION_COMBINED = VERSION_COMBINED;
ccs.VERSION_CHANGE_ROTATION_RANGE = VERSION_CHANGE_ROTATION_RANGE;
ccs.VERSION_COLOR_READING = VERSION_COLOR_READING;
ccs.MAX_VERTEXZ_VALUE = MAX_VERTEXZ_VALUE;
ccs.ARMATURE_MAX_CHILD = ARMATURE_MAX_CHILD;
ccs.ARMATURE_MAX_ZORDER = ARMATURE_MAX_ZORDER;
ccs.ARMATURE_MAX_COUNT = ARMATURE_MAX_COUNT;
ccs.AUTO_ADD_SPRITE_FRAME_NAME_PREFIX = AUTO_ADD_SPRITE_FRAME_NAME_PREFIX;
ccs.ENABLE_PHYSICS_CHIPMUNK_DETECT = ENABLE_PHYSICS_CHIPMUNK_DETECT;
ccs.ENABLE_PHYSICS_SAVE_CALCULATED_VERTEX = ENABLE_PHYSICS_SAVE_CALCULATED_VERTEX;
ccs.displayFactory = displayFactory;
ccs.PT_RATIO = PT_RATIO;
ccs.armatureDataManager = armatureDataManager;
ccs.CONST_VERSION = CONST_VERSION;
ccs.CONST_VERSION_2_0 = CONST_VERSION_2_0;
ccs.CONST_VERSION_COMBINED = CONST_VERSION_COMBINED;
ccs.CONST_ARMATURES = CONST_ARMATURES;
ccs.CONST_ARMATURE = CONST_ARMATURE;
ccs.CONST_BONE = CONST_BONE;
ccs.CONST_DISPLAY = CONST_DISPLAY;
ccs.CONST_ANIMATIONS = CONST_ANIMATIONS;
ccs.CONST_ANIMATION = CONST_ANIMATION;
ccs.CONST_MOVEMENT = CONST_MOVEMENT;
ccs.CONST_FRAME = CONST_FRAME;
ccs.CONST_TEXTURE_ATLAS = CONST_TEXTURE_ATLAS;
ccs.CONST_SUB_TEXTURE = CONST_SUB_TEXTURE;
ccs.CONST_SKELETON = CONST_SKELETON;
ccs.CONST_A_NAME = CONST_A_NAME;
ccs.CONST_A_DURATION = CONST_A_DURATION;
ccs.CONST_A_FRAME_INDEX = CONST_A_FRAME_INDEX;
ccs.CONST_A_DURATION_TO = CONST_A_DURATION_TO;
ccs.CONST_A_DURATION_TWEEN = CONST_A_DURATION_TWEEN;
ccs.CONST_A_LOOP = CONST_A_LOOP;
ccs.CONST_A_MOVEMENT_SCALE = CONST_A_MOVEMENT_SCALE;
ccs.CONST_A_MOVEMENT_DELAY = CONST_A_MOVEMENT_DELAY;
ccs.CONST_A_DISPLAY_INDEX = CONST_A_DISPLAY_INDEX;
ccs.CONST_A_PLIST = CONST_A_PLIST;
ccs.CONST_A_PARENT = CONST_A_PARENT;
ccs.CONST_A_SKEW_X = CONST_A_SKEW_X;
ccs.CONST_A_SKEW_Y = CONST_A_SKEW_Y;
ccs.CONST_A_SCALE_X = CONST_A_SCALE_X;
ccs.CONST_A_SCALE_Y = CONST_A_SCALE_Y;
ccs.CONST_A_Z = CONST_A_Z;
ccs.CONST_A_EVENT = CONST_A_EVENT;
ccs.CONST_A_SOUND = CONST_A_SOUND;
ccs.CONST_A_SOUND_EFFECT = CONST_A_SOUND_EFFECT;
ccs.CONST_A_TWEEN_EASING = CONST_A_TWEEN_EASING;
ccs.CONST_A_EASING_PARAM = CONST_A_EASING_PARAM;
ccs.CONST_A_TWEEN_ROTATE = CONST_A_TWEEN_ROTATE;
ccs.CONST_A_IS_ARMATURE = CONST_A_IS_ARMATURE;
ccs.CONST_A_DISPLAY_TYPE = CONST_A_DISPLAY_TYPE;
ccs.CONST_A_MOVEMENT = CONST_A_MOVEMENT;
ccs.CONST_A_X = CONST_A_X;
ccs.CONST_A_Y = CONST_A_Y;
ccs.CONST_A_COCOS2DX_X = CONST_A_COCOS2DX_X;
ccs.CONST_A_COCOS2DX_Y = CONST_A_COCOS2DX_Y;
ccs.CONST_A_WIDTH = CONST_A_WIDTH;
ccs.CONST_A_HEIGHT = CONST_A_HEIGHT;
ccs.CONST_A_PIVOT_X = CONST_A_PIVOT_X;
ccs.CONST_A_PIVOT_Y = CONST_A_PIVOT_Y;
ccs.CONST_A_COCOS2D_PIVOT_X = CONST_A_COCOS2D_PIVOT_X;
ccs.CONST_A_COCOS2D_PIVOT_Y = CONST_A_COCOS2D_PIVOT_Y;
ccs.CONST_A_BLEND_TYPE = CONST_A_BLEND_TYPE;
ccs.CONST_A_BLEND_SRC = CONST_A_BLEND_SRC;
ccs.CONST_A_BLEND_DST = CONST_A_BLEND_DST;
ccs.CONST_A_ALPHA = CONST_A_ALPHA;
ccs.CONST_A_RED = CONST_A_RED;
ccs.CONST_A_GREEN = CONST_A_GREEN;
ccs.CONST_A_BLUE = CONST_A_BLUE;
ccs.CONST_A_ALPHA_OFFSET = CONST_A_ALPHA_OFFSET;
ccs.CONST_A_RED_OFFSET = CONST_A_RED_OFFSET;
ccs.CONST_A_GREEN_OFFSET = CONST_A_GREEN_OFFSET;
ccs.CONST_A_BLUE_OFFSET = CONST_A_BLUE_OFFSET;
ccs.CONST_A_COLOR_TRANSFORM = CONST_A_COLOR_TRANSFORM;
ccs.CONST_A_TWEEN_FRAME = CONST_A_TWEEN_FRAME;
ccs.CONST_CONTOUR = CONST_CONTOUR;
ccs.CONST_CONTOUR_VERTEX = CONST_CONTOUR_VERTEX;
ccs.CONST_FL_NAN = CONST_FL_NAN;
ccs.CONST_FRAME_DATA = CONST_FRAME_DATA;
ccs.CONST_MOVEMENT_BONE_DATA = CONST_MOVEMENT_BONE_DATA;
ccs.CONST_MOVEMENT_DATA = CONST_MOVEMENT_DATA;
ccs.CONST_ANIMATION_DATA = CONST_ANIMATION_DATA;
ccs.CONST_DISPLAY_DATA = CONST_DISPLAY_DATA;
ccs.CONST_SKIN_DATA = CONST_SKIN_DATA;
ccs.CONST_BONE_DATA = CONST_BONE_DATA;
ccs.CONST_ARMATURE_DATA = CONST_ARMATURE_DATA;
ccs.CONST_CONTOUR_DATA = CONST_CONTOUR_DATA;
ccs.CONST_TEXTURE_DATA = CONST_TEXTURE_DATA;
ccs.CONST_VERTEX_POINT = CONST_VERTEX_POINT;
ccs.CONST_COLOR_INFO = CONST_COLOR_INFO;
ccs.CONST_CONFIG_FILE_PATH = CONST_CONFIG_FILE_PATH;
ccs.CONST_CONTENT_SCALE = CONST_CONTENT_SCALE;
ccs.dataReaderHelper = dataReaderHelper;
ccs.BLEND_TYPE_NORMAL = BLEND_TYPE_NORMAL;
ccs.BLEND_TYPE_LAYER = BLEND_TYPE_LAYER;
ccs.BLEND_TYPE_DARKEN = BLEND_TYPE_DARKEN;
ccs.BLEND_TYPE_MULTIPLY = BLEND_TYPE_MULTIPLY;
ccs.BLEND_TYPE_LIGHTEN = BLEND_TYPE_LIGHTEN;
ccs.BLEND_TYPE_SCREEN = BLEND_TYPE_SCREEN;
ccs.BLEND_TYPE_OVERLAY = BLEND_TYPE_OVERLAY;
ccs.BLEND_TYPE_HIGHLIGHT = BLEND_TYPE_HIGHLIGHT;
ccs.BLEND_TYPE_ADD = BLEND_TYPE_ADD;
ccs.BLEND_TYPE_SUBTRACT = BLEND_TYPE_SUBTRACT;
ccs.BLEND_TYPE_DIFFERENCE = BLEND_TYPE_DIFFERENCE;
ccs.BLEND_TYPE_INVERT = BLEND_TYPE_INVERT;
ccs.BLEND_TYPE_ALPHA = BLEND_TYPE_ALPHA;
ccs.BLEND_TYPE_ERASE = BLEND_TYPE_ERASE;
ccs.DISPLAY_TYPE_SPRITE = DISPLAY_TYPE_SPRITE;
ccs.DISPLAY_TYPE_ARMATURE = DISPLAY_TYPE_ARMATURE;
ccs.DISPLAY_TYPE_PARTICLE = DISPLAY_TYPE_PARTICLE;
ccs.DISPLAY_TYPE_MAX = DISPLAY_TYPE_MAX;
ccs.spriteFrameCacheHelper = spriteFrameCacheHelper;
ccs.SPRITE_CONTAIN_POINT = SPRITE_CONTAIN_POINT;
ccs.SPRITE_CONTAIN_POINT_WITH_RETURN = SPRITE_CONTAIN_POINT_WITH_RETURN;
ccs.actionTimelineCache = actionTimelineCache;
ccs.csLoader = csLoader;
ccs._load = _ccsLoad;
ccs.InnerActionType = InnerActionType;
ccs.objectFactory = objectFactory;
ccs.triggerManager = triggerManager;
