export const KEYBOARD_RETURNTYPE_DEFAULT = 0;
export const KEYBOARD_RETURNTYPE_DONE = 1;
export const KEYBOARD_RETURNTYPE_SEND = 2;
export const KEYBOARD_RETURNTYPE_SEARCH = 3;
export const KEYBOARD_RETURNTYPE_GO = 4;

export const EDITBOX_INPUT_MODE_ANY = 0;
export const EDITBOX_INPUT_MODE_EMAILADDR = 1;
export const EDITBOX_INPUT_MODE_NUMERIC = 2;
export const EDITBOX_INPUT_MODE_PHONENUMBER = 3;
export const EDITBOX_INPUT_MODE_URL = 4;
export const EDITBOX_INPUT_MODE_DECIMAL = 5;
export const EDITBOX_INPUT_MODE_SINGLELINE = 6;

export const EDITBOX_INPUT_FLAG_PASSWORD = 0;
export const EDITBOX_INPUT_FLAG_SENSITIVE = 1;
export const EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD = 2;
export const EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE = 3;
export const EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS = 4;
