import { EditBoxDelegate, EditBox } from './edit-box';
import { EditBoxCanvasRenderCmd } from './edit-box-canvas-render-cmd';
import { EditBoxWebGLRenderCmd } from './edit-box-webgl-render-cmd';
import { editBoxPolyfill } from './edit-box-impl';
import {
    KEYBOARD_RETURNTYPE_DEFAULT,
    KEYBOARD_RETURNTYPE_DONE,
    KEYBOARD_RETURNTYPE_SEND,
    KEYBOARD_RETURNTYPE_SEARCH,
    KEYBOARD_RETURNTYPE_GO,
    EDITBOX_INPUT_MODE_ANY,
    EDITBOX_INPUT_MODE_EMAILADDR,
    EDITBOX_INPUT_MODE_NUMERIC,
    EDITBOX_INPUT_MODE_PHONENUMBER,
    EDITBOX_INPUT_MODE_URL,
    EDITBOX_INPUT_MODE_DECIMAL,
    EDITBOX_INPUT_MODE_SINGLELINE,
    EDITBOX_INPUT_FLAG_PASSWORD,
    EDITBOX_INPUT_FLAG_SENSITIVE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS
} from './constants';

// Wire render commands
EditBox.CanvasRenderCmd = EditBoxCanvasRenderCmd;
EditBox.WebGLRenderCmd = EditBoxWebGLRenderCmd;

// Wire polyfill reference
EditBox._polyfill = editBoxPolyfill;

// cc globals (backward compatibility)


export {
    EditBoxDelegate,
    EditBox,
    EditBoxCanvasRenderCmd,
    EditBoxWebGLRenderCmd,
    editBoxPolyfill,
    KEYBOARD_RETURNTYPE_DEFAULT,
    KEYBOARD_RETURNTYPE_DONE,
    KEYBOARD_RETURNTYPE_SEND,
    KEYBOARD_RETURNTYPE_SEARCH,
    KEYBOARD_RETURNTYPE_GO,
    EDITBOX_INPUT_MODE_ANY,
    EDITBOX_INPUT_MODE_EMAILADDR,
    EDITBOX_INPUT_MODE_NUMERIC,
    EDITBOX_INPUT_MODE_PHONENUMBER,
    EDITBOX_INPUT_MODE_URL,
    EDITBOX_INPUT_MODE_DECIMAL,
    EDITBOX_INPUT_MODE_SINGLELINE,
    EDITBOX_INPUT_FLAG_PASSWORD,
    EDITBOX_INPUT_FLAG_SENSITIVE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS
};
