import { EditBoxDelegate, EditBox } from './edit-box';
import { EditBoxCanvasRenderCmd } from './edit-box-canvas-render-cmd';
import { EditBoxWebGLRenderCmd } from './edit-box-webgl-render-cmd';
import { editBoxPolyfill } from './edit-box-impl';
import {
    KEYBOARD_RETURNTYPE_DEFAULT,
    KEYBOARD_RETURNTYPE_DONE,
    KEYBOARD_RETURNTYPE_SEND,
    KEYBOARD_RETURNTYPE_SEARCH,
    KEYBOARD_RETURNTYPE_GO,
    EDITBOX_INPUT_MODE_ANY,
    EDITBOX_INPUT_MODE_EMAILADDR,
    EDITBOX_INPUT_MODE_NUMERIC,
    EDITBOX_INPUT_MODE_PHONENUMBER,
    EDITBOX_INPUT_MODE_URL,
    EDITBOX_INPUT_MODE_DECIMAL,
    EDITBOX_INPUT_MODE_SINGLELINE,
    EDITBOX_INPUT_FLAG_PASSWORD,
    EDITBOX_INPUT_FLAG_SENSITIVE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS
} from './constants';

// Wire render commands
EditBox.CanvasRenderCmd = EditBoxCanvasRenderCmd;
EditBox.WebGLRenderCmd = EditBoxWebGLRenderCmd;

// Wire polyfill reference
EditBox._polyfill = editBoxPolyfill;

// cc globals (backward compatibility)
cc.KEYBOARD_RETURNTYPE_DEFAULT = KEYBOARD_RETURNTYPE_DEFAULT;
cc.KEYBOARD_RETURNTYPE_DONE = KEYBOARD_RETURNTYPE_DONE;
cc.KEYBOARD_RETURNTYPE_SEND = KEYBOARD_RETURNTYPE_SEND;
cc.KEYBOARD_RETURNTYPE_SEARCH = KEYBOARD_RETURNTYPE_SEARCH;
cc.KEYBOARD_RETURNTYPE_GO = KEYBOARD_RETURNTYPE_GO;

cc.EDITBOX_INPUT_MODE_ANY = EDITBOX_INPUT_MODE_ANY;
cc.EDITBOX_INPUT_MODE_EMAILADDR = EDITBOX_INPUT_MODE_EMAILADDR;
cc.EDITBOX_INPUT_MODE_NUMERIC = EDITBOX_INPUT_MODE_NUMERIC;
cc.EDITBOX_INPUT_MODE_PHONENUMBER = EDITBOX_INPUT_MODE_PHONENUMBER;
cc.EDITBOX_INPUT_MODE_URL = EDITBOX_INPUT_MODE_URL;
cc.EDITBOX_INPUT_MODE_DECIMAL = EDITBOX_INPUT_MODE_DECIMAL;
cc.EDITBOX_INPUT_MODE_SINGLELINE = EDITBOX_INPUT_MODE_SINGLELINE;

cc.EDITBOX_INPUT_FLAG_PASSWORD = EDITBOX_INPUT_FLAG_PASSWORD;
cc.EDITBOX_INPUT_FLAG_SENSITIVE = EDITBOX_INPUT_FLAG_SENSITIVE;
cc.EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD = EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD;
cc.EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE = EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE;
cc.EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS = EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS;

cc.EditBoxDelegate = EditBoxDelegate;
cc.EditBox = EditBox;

export {
    EditBoxDelegate,
    EditBox,
    EditBoxCanvasRenderCmd,
    EditBoxWebGLRenderCmd,
    editBoxPolyfill,
    KEYBOARD_RETURNTYPE_DEFAULT,
    KEYBOARD_RETURNTYPE_DONE,
    KEYBOARD_RETURNTYPE_SEND,
    KEYBOARD_RETURNTYPE_SEARCH,
    KEYBOARD_RETURNTYPE_GO,
    EDITBOX_INPUT_MODE_ANY,
    EDITBOX_INPUT_MODE_EMAILADDR,
    EDITBOX_INPUT_MODE_NUMERIC,
    EDITBOX_INPUT_MODE_PHONENUMBER,
    EDITBOX_INPUT_MODE_URL,
    EDITBOX_INPUT_MODE_DECIMAL,
    EDITBOX_INPUT_MODE_SINGLELINE,
    EDITBOX_INPUT_FLAG_PASSWORD,
    EDITBOX_INPUT_FLAG_SENSITIVE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS
};
