import { EditBox } from './edit-box';
import { EditBoxInputBase } from './edit-box-input-base';
import { DesktopEditBoxInput } from './edit-box-input-desktop';
import { MobileEditBoxInput, editBoxPolyfill } from './edit-box-input-mobile';
import {
    KEYBOARD_RETURNTYPE_DEFAULT,
    KEYBOARD_RETURNTYPE_DONE,
    KEYBOARD_RETURNTYPE_SEND,
    KEYBOARD_RETURNTYPE_SEARCH,
    KEYBOARD_RETURNTYPE_GO,
    EDITBOX_INPUT_MODE_ANY,
    EDITBOX_INPUT_MODE_EMAILADDR,
    EDITBOX_INPUT_MODE_NUMERIC,
    EDITBOX_INPUT_MODE_PHONENUMBER,
    EDITBOX_INPUT_MODE_URL,
    EDITBOX_INPUT_MODE_DECIMAL,
    EDITBOX_INPUT_MODE_SINGLELINE,
    EDITBOX_INPUT_FLAG_PASSWORD,
    EDITBOX_INPUT_FLAG_SENSITIVE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS
} from './constants';

// Backwards-compat handle for the Android Sougou/360 zoom polyfill flag
EditBox._polyfill = editBoxPolyfill;

export {
    EditBox,
    EditBoxInputBase,
    DesktopEditBoxInput,
    MobileEditBoxInput,
    editBoxPolyfill,
    KEYBOARD_RETURNTYPE_DEFAULT,
    KEYBOARD_RETURNTYPE_DONE,
    KEYBOARD_RETURNTYPE_SEND,
    KEYBOARD_RETURNTYPE_SEARCH,
    KEYBOARD_RETURNTYPE_GO,
    EDITBOX_INPUT_MODE_ANY,
    EDITBOX_INPUT_MODE_EMAILADDR,
    EDITBOX_INPUT_MODE_NUMERIC,
    EDITBOX_INPUT_MODE_PHONENUMBER,
    EDITBOX_INPUT_MODE_URL,
    EDITBOX_INPUT_MODE_DECIMAL,
    EDITBOX_INPUT_MODE_SINGLELINE,
    EDITBOX_INPUT_FLAG_PASSWORD,
    EDITBOX_INPUT_FLAG_SENSITIVE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_WORD,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_SENTENCE,
    EDITBOX_INPUT_FLAG_INITIAL_CAPS_ALL_CHARACTERS
};
